function a(){
    try{
        let a = 5/0;
    }
    catch(err){
        console.log("0");
    }
}
a();